"""checking adding function

Revision ID: 538dd8dcab42
Revises: eb537bed453b
Create Date: 2023-12-17 12:12:59.189476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538dd8dcab42'
down_revision = 'eb537bed453b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
