"""added books and user methods in database.py and initialized them in bookLibrary.py

Revision ID: 800202e70e94
Revises: 538dd8dcab42
Create Date: 2023-12-17 14:15:11.896432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800202e70e94'
down_revision = '538dd8dcab42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
