"""seeded random fake data to tables

Revision ID: b1b48fb2652a
Revises: 364f29ad6c96
Create Date: 2023-12-17 11:02:28.641767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b48fb2652a'
down_revision = '364f29ad6c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookCheckout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookCheckout',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('bookID', sa.INTEGER(), nullable=True),
    sa.Column('userID', sa.INTEGER(), nullable=True),
    sa.Column('genre', sa.VARCHAR(), nullable=True),
    sa.Column('checkoutDate', sa.DATE(), nullable=True),
    sa.Column('returnDate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
