"""updated seed file

Revision ID: eb537bed453b
Revises: c25c9ad3327d
Create Date: 2023-12-17 11:20:58.866153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb537bed453b'
down_revision = 'c25c9ad3327d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
